# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aacb0163a648bcf736b5e2f21dd1f975db88abd40518b15470bc53a926f0f2a50b2c8d37107c57621d21201e9aa57972b8e5b5f9fc178369881c864bbbc6a2df

test:
  secret_key_base: a2f0c7da6c1616919199ad0a196eac7801b84a2c7b1a1f266e74eb5177f789261cce90d84f980652e276c7f2c79c0b70809ce388f8c47b0017a76603c36bd3b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
